version: 2.1

orbs:
  unity: game-ci/unity@1.1

workflows:
  build-unity-project:
    jobs:
      # Linux
      # - unity/test:
      #     name: 'test-linux'
      #     step-name: 'Check if the tests run and results are uploaded'
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     executor:
      #       name: 'unity/ubuntu'
      #       target_platform: 'linux-il2cpp'
      #       editor_version: '2021.3.1f1'
      #       resource_class: 'medium'
      #     project-path: 'Unity2D-Demo-Game-CI-CD/src'
      #     test-platform: 'playmode'
      #     context: unity

      # Windows
      - unity/test:
          name: 'test-windows'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            size: 'large'
            editor_version: '2021.3.2f1'
            target_platform: 'windows-il2cpp'
          project-path: 'learn_unity2d_platform'
          test-platform: 'playmode'
          context: unity

      # # macOS
      # - unity/test:
      #     name: 'test-osx'
      #     step-name: 'Check if the tests run and results are uploaded'
      #     unity-license-var-name: 'UNITY_ENCODED_LICENSE'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     executor:
      #       name: 'unity/macos'
      #       editor_version: '2021.3.1f1'
      #       resource_class: 'large'
      #     project-path: 'Unity2D-Demo-Game-CI-CD/src'
      #     test-platform: 'playmode'
      #     context: unity
